# Generated by Django 2.0 on 2020-06-07 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Strpic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='海报内容')),
                ('link', models.CharField(max_length=100, null=True, verbose_name='链接')),
                ('qrcode', models.ImageField(upload_to='upload', verbose_name='二维码')),
                ('background', models.CharField(default='#1E90FF', max_length=50, verbose_name='背景色')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
    ]
