# Generated by Django 2.0 on 2020-06-06 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Strpic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('pic_url', models.FileField(upload_to='codepic/')),
                ('background', models.CharField(choices=[('red', '红色'), ('black', '黑色'), ('blue', '蓝色')], max_length=50)),
            ],
        ),
    ]
