# Generated by Django 2.0 on 2020-06-07 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='strpic',
            old_name='link',
            new_name='link_url',
        ),
        migrations.AddField(
            model_name='strpic',
            name='link_name',
            field=models.CharField(max_length=100, null=True, verbose_name='链接名'),
        ),
    ]
