# Generated by Django 2.0 on 2020-06-07 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_auto_20200607_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='strpic',
            name='link_qrcode',
            field=models.ImageField(null=True, upload_to='generate_qrcode', verbose_name='生成二维码'),
        ),
        migrations.AlterField(
            model_name='strpic',
            name='qrcode',
            field=models.ImageField(null=True, upload_to='upload_qrcode', verbose_name='上传二维码'),
        ),
    ]
