# Generated by Django 2.0 on 2020-06-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_auto_20200606_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strpic',
            name='pic_url',
            field=models.ImageField(upload_to='upload'),
        ),
    ]
